"use client";
import React, { useState } from "react";
import { FileUpload } from "@/components/ui/file-upload";

function FileUploadDemo() {
    const [files, setFiles] = useState<File[]>([]);
    const handleFileUpload = (files: File[]) => {
        setFiles(files);
        console.log(files);
    };

    return (
        <>
            <div className="w-full max-w-4xl mx-auto min-h-96 border border-dashed bg-white dark:bg-black border-neutral-200 dark:border-neutral-800 rounded-lg">
                <FileUpload onChange={handleFileUpload} />
            </div>

            <div>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus quo ullam commodi doloremque temporibus. Esse quam, quasi iste, inventore quae eius cumque tempora ea ad laborum, quaerat minima hic aliquam!
                Quam perferendis adipisci cupiditate eaque officiis quae? Earum voluptates aspernatur asperiores facere at eveniet sunt magni eius, iure ipsa possimus natus corrupti harum maxime illo fugiat voluptas blanditiis debitis! Ipsum.
                Veniam delectus quisquam accusantium exercitationem quas numquam nulla iste dignissimos! Provident ipsum aliquid eum quae! Temporibus voluptatibus placeat beatae. Blanditiis quibusdam dolore exercitationem vero porro laborum quaerat voluptatibus optio at!
                Perspiciatis error reprehenderit nemo eveniet culpa optio quos repudiandae pariatur libero quidem iusto id, quibusdam obcaecati vitae. Iusto consequatur cumque obcaecati qui laborum labore nemo, minus dolore ab molestias similique?
                Pariatur assumenda magnam, aut sapiente veniam dolorum voluptatum reprehenderit, et quae delectus iste expedita voluptatem facilis sunt tenetur mollitia alias provident animi id consequuntur culpa modi incidunt, deleniti quia! Magnam.
                Debitis officia hic amet, dolore laboriosam vitae ullam laborum pariatur velit id iste ipsam, atque, magnam est nemo aperiam consequuntur cum quasi distinctio omnis harum. Perspiciatis sint maiores porro nihil?
                Tenetur maxime alias fugiat, minima nihil dolorum iusto quasi iure dolorem autem officiis atque hic sit reprehenderit eum, voluptatem recusandae rerum aliquam porro illo itaque ex vel. Ipsa, assumenda culpa.
                Beatae tempore vitae reiciendis cupiditate, sapiente animi obcaecati! Vero dignissimos commodi odit eligendi tempora maiores ratione libero, rerum nam ad voluptates cum suscipit vitae iusto omnis deleniti explicabo! Nemo, saepe!
                Commodi temporibus reiciendis quisquam cum, quae accusantium beatae! Facilis quas deleniti delectus quaerat iste a? Earum dolor ipsa fugit, mollitia iusto, voluptate facere explicabo necessitatibus cupiditate eos iste eligendi officiis!
                Vitae alias iusto voluptate magnam optio pariatur totam cum maxime facilis nobis. Quos officia numquam eos esse beatae possimus adipisci debitis dolorum nemo, nihil ducimus reiciendis eum corporis, ipsa architecto.
                Fuga veritatis laudantium, eius cumque magni ea numquam architecto nobis eum ipsum nostrum, minus ab delectus iure eos beatae? Autem, quod quis neque aperiam porro similique maxime minima deleniti adipisci.
                Possimus ut quasi vitae dolor harum doloremque, excepturi hic, minus totam non labore architecto ab aut ad numquam! Laborum eaque, voluptates fugit neque quis iusto maxime non dicta cum dolorum.
                Laboriosam maiores quod dolores tempora nostrum. Sit cumque unde quam temporibus qui aspernatur iste dolorum officia culpa facilis? Laudantium assumenda voluptatem alias quia! Illum praesentium aliquam cumque, nihil asperiores odio?
                Harum adipisci at numquam? Consequuntur perferendis officiis quod nisi tempora in inventore mollitia, laborum rerum aperiam magnam nostrum praesentium. Laboriosam et sint incidunt autem magnam earum, quasi repellendus rem debitis?
                Odio qui corrupti sit id eaque commodi voluptatibus ea repellat porro, reiciendis, assumenda laboriosam velit dolores! Ad dolore quo aspernatur aperiam. Possimus fuga minima culpa quam, alias inventore ab illo!
                Minima consequatur animi consequuntur recusandae! Corrupti, quae deleniti quod earum quisquam eligendi possimus in voluptates nulla, quam eaque, modi dicta beatae? Amet totam dolor veniam quam, necessitatibus quae voluptatum nisi?
                Tempora alias officia odio dolor eligendi aliquam aspernatur consequuntur eaque modi nobis optio, eius harum, consequatur dolore quo iusto. Eum dolor ipsa debitis neque facilis, facere corrupti? Beatae, magni molestiae?
                Nam velit hic illum odio sint nisi voluptas, in distinctio, necessitatibus reiciendis repellendus. Vitae aspernatur exercitationem aut. Error voluptatibus unde culpa molestias, quas voluptatem optio qui id praesentium commodi tempore.
                Velit atque iure nihil provident reprehenderit quas perspiciatis explicabo dicta inventore iste veritatis asperiores, nisi, excepturi non, voluptate quis corporis deleniti facere est modi? Ea accusamus voluptatum dolorem maxime nostrum?
                Rem id commodi dicta ea laborum nisi omnis provident ut, molestiae cum voluptate quidem soluta? Eaque, magnam doloremque quibusdam necessitatibus molestias temporibus rerum dolores cum laboriosam voluptatum. Inventore, cupiditate quia.
                Corrupti, nisi minus est harum sit animi rerum perferendis exercitationem sint explicabo, accusantium dolorem voluptate a eius dolore officiis aut vel pariatur placeat ea beatae? Asperiores saepe dolorum dolore unde!
                Earum quibusdam tenetur commodi, nesciunt, ut, dicta modi omnis deleniti consequatur aliquid totam voluptas dolorem velit quo. Praesentium, odit eius quibusdam pariatur inventore accusamus iusto distinctio sint repellat nesciunt assumenda.
                Dolores cumque soluta quae quia, ab recusandae hic reiciendis explicabo consequatur ducimus omnis maxime fugit odit enim ex velit laboriosam ipsam quaerat dolorum provident. Dolorum accusantium excepturi dicta temporibus officiis!
                Facilis, quibusdam? Aliquam, dolores qui obcaecati odit iusto vero perspiciatis inventore reiciendis voluptatum commodi eaque delectus sunt officiis ut cupiditate architecto sapiente voluptate recusandae error suscipit. Animi esse unde quae?
                Enim dolores debitis iusto necessitatibus neque sed aut aspernatur vel perferendis delectus harum laborum rerum quis, ducimus amet et nemo aliquam nostrum minima! Similique eius velit vero facere qui id.
                Quasi ipsa accusamus nemo eligendi quae doloremque commodi inventore. Modi molestias blanditiis recusandae ipsam facilis, aliquam deserunt itaque tempore debitis nobis, necessitatibus hic architecto harum libero excepturi rem assumenda. Voluptatibus?
                Eos, magnam autem fugiat reprehenderit magni corrupti sit? Tenetur doloremque quibusdam dignissimos cumque doloribus officiis excepturi veritatis reprehenderit obcaecati earum? Deserunt nihil quod praesentium repudiandae eaque recusandae porro aperiam neque!
                Porro veritatis non numquam dignissimos ad reprehenderit ex odio doloribus doloremque, illum saepe exercitationem soluta debitis eligendi quos ut dicta. Fuga sunt quas, exercitationem aliquid similique culpa ut quisquam nisi.
                Similique veritatis dolorum repellendus! Nobis provident quae minima iure cum eum beatae voluptatum, culpa quos corporis. Quaerat sed voluptatum quisquam veritatis rerum, veniam, qui nihil fugit assumenda autem perferendis quasi.
                Obcaecati, cum dolor, totam explicabo labore eveniet rem voluptas omnis facere ipsum nisi vitae eum deserunt, assumenda animi natus consectetur accusantium eos. Exercitationem provident, earum doloribus accusamus vero quam animi.
                Deleniti dignissimos at beatae repellat a. Minus nisi, ab ad qui ipsam provident alias ducimus cum saepe officia. Maxime ratione rem doloribus vel pariatur vitae numquam deserunt omnis quidem fugit?
                Vitae, autem voluptatibus dolor quas veniam quidem, culpa maiores numquam pariatur repellat distinctio sunt rerum tempora reprehenderit architecto nemo dolores natus voluptas ea quae assumenda inventore. Accusamus nisi fugit saepe.
                Eos non est facilis consequatur ratione facere dolorem quasi! Voluptates, corrupti repellendus provident ex ducimus sunt, sint iusto tempore amet ipsam, minima expedita officiis illum explicabo nihil ipsa nulla quae!
                Odit ipsa, distinctio numquam sunt vel saepe accusantium facilis nulla! Accusantium consequatur ipsa nostrum, repellendus explicabo fuga dicta. Quam autem incidunt possimus cum dolorem quibusdam eos dolorum quasi! Blanditiis, omnis.
                Optio minima harum minus iusto deserunt a corporis. Voluptatum error modi ex obcaecati cumque necessitatibus, nulla cum enim debitis pariatur, commodi quod repellat voluptates. Dolores eum vero blanditiis sint in.
                Voluptates, dolorem cumque, voluptatibus maiores accusantium perspiciatis nostrum unde rem magni laboriosam consectetur ratione reiciendis quisquam, enim perferendis. Laudantium facere provident quae voluptates. Officia culpa tenetur hic sint. Saepe, illo.
                Culpa, praesentium. Culpa nam, totam quis beatae voluptatem earum non, dicta sed, deserunt sint quae deleniti illum. Eum saepe corporis ullam enim eveniet quasi beatae, exercitationem est consequatur. Nulla, fugiat!
                Enim, ab assumenda corrupti rerum at, dolorum maxime placeat molestiae voluptatum qui possimus cumque quas saepe commodi explicabo earum. Eos, repudiandae rem. Omnis architecto quo odit. Laboriosam, atque! Vitae, suscipit!
                Consectetur, laudantium harum, hic consequuntur inventore eius quis cumque magnam accusantium ratione repellat quaerat eveniet non iste doloribus dolores. Perferendis perspiciatis a dolores quia ipsam aliquam ex voluptates, accusamus alias.
                Quasi quod blanditiis mollitia quidem possimus repellat iste earum sunt itaque magni a ipsum aspernatur deleniti, autem porro facilis quos, sed ullam asperiores vero! Eos ratione magni tenetur sequi quas!
                Mollitia sunt exercitationem iusto, quam harum quibusdam. Est placeat eius illum commodi vel esse et quidem modi, sunt sapiente beatae, ipsum nobis, saepe totam distinctio. Alias debitis eos ipsa eaque?
                Doloremque sed, facilis tenetur sunt minima voluptatum saepe cumque ab. Voluptas reprehenderit unde excepturi animi quasi et incidunt adipisci, officia libero delectus ipsam cum eveniet sit corrupti nam esse at.
                Qui mollitia magnam accusamus placeat ducimus tempore iure earum asperiores quae odio quia, assumenda hic sunt soluta unde fugit nulla, officia tenetur minus excepturi rem repellat. Optio nemo quod magnam?
                Ipsum, recusandae earum? Debitis saepe, facere voluptate deleniti ab odit nulla vero adipisci enim sunt! Corporis nesciunt animi officiis esse repudiandae praesentium quaerat nostrum eligendi assumenda odio. Enim, repellendus provident?
                Hic, sapiente? Provident, quam. Dicta nesciunt laborum voluptate aspernatur labore voluptas reiciendis, itaque, nisi aperiam totam dolor rem quisquam quaerat eius? Voluptas voluptates aspernatur, amet nostrum voluptatibus obcaecati at blanditiis.
                Minus eligendi officia id voluptates consequatur inventore labore provident in beatae nobis ducimus aliquid, nihil laudantium amet voluptatem autem, porro repellendus illum vero fugiat nemo quae, est cupiditate! Nemo, suscipit.
                Eos, excepturi a! At impedit nobis ipsam temporibus alias magnam tenetur. Labore harum nesciunt quae odit animi hic rerum quam, laboriosam ipsam delectus, ab, repellendus enim nam dignissimos autem beatae.
                Minus, cum delectus pariatur similique non molestias nobis expedita ducimus laudantium veniam porro iure numquam, assumenda beatae autem nesciunt. Reiciendis tempora accusantium dolor architecto nemo, dicta eos consequuntur officiis accusamus!
                Autem illo deserunt commodi modi, facilis vitae quas eius nam perspiciatis magni, dignissimos asperiores illum consequatur sit voluptas odio. Libero doloremque aspernatur repellat maxime modi deleniti cum suscipit alias ab?
                Cupiditate tempore hic dicta molestias alias illo, commodi natus ducimus. Doloremque, suscipit! Inventore necessitatibus beatae magni autem! Porro sunt autem sit officiis. Id molestias rerum eos quia harum? Eum, doloribus?
                Dicta eum, necessitatibus id molestias voluptatem magni. Voluptates consectetur ullam ducimus quos, et beatae, doloremque vero voluptatem quia molestias doloribus optio cupiditate provident sapiente at pariatur neque excepturi eaque dolorem?
                Sequi nihil dolorem, in, nostrum earum officia quidem ratione tempora accusantium voluptatem soluta ipsa eveniet. Maiores earum ullam obcaecati, reiciendis recusandae natus et nemo cupiditate facere voluptatibus. Amet, culpa et.
                Distinctio consequatur qui illum optio neque quod animi hic accusamus voluptatum, libero ut laudantium, laboriosam nulla assumenda reiciendis porro mollitia commodi, ipsum ipsam eum sit maxime sed. Voluptates, quis molestias?
                Ipsum assumenda quisquam rerum quia laudantium quas incidunt? Eligendi eum expedita vel officiis quos id nesciunt, eaque voluptatem alias impedit, laboriosam nobis modi qui facilis perspiciatis, atque harum. Magnam, alias!
                Harum iste reiciendis dolor saepe praesentium. Commodi quos aperiam ratione quaerat dolores unde reiciendis ut culpa in ipsa quae voluptates ducimus impedit doloremque perferendis fuga voluptatem tempora, debitis placeat quidem.
                Deserunt explicabo magni aspernatur pariatur vel veritatis quisquam autem doloremque iusto id numquam quia, iure soluta cum, quis, ipsam odio fuga est exercitationem inventore natus! Praesentium deleniti dicta aspernatur blanditiis?
                Dolorem, amet saepe animi molestiae, sed aut dicta fugit, ipsa magnam in fugiat exercitationem ad incidunt ut pariatur! Consequatur inventore ratione eum dolore accusantium ab veritatis sint ipsam illo labore!
                Non quos ipsa odio quibusdam illo ipsum porro itaque. Repellat labore officiis consectetur at quasi sequi aspernatur voluptate, asperiores non quod esse, debitis accusantium maiores corrupti dolorum quia veritatis. Dolores.
                Similique repellendus voluptate dolor earum ducimus iste fuga quo possimus provident optio. Recusandae laudantium voluptatem tempora perspiciatis doloribus libero dicta consequuntur omnis fugiat ducimus voluptates accusamus, rem aspernatur commodi neque.
                Maxime tenetur ad quas et ex quis voluptate dolorum molestiae totam delectus consequuntur temporibus corrupti error maiores, quo voluptatem natus dolorem dolore. Eaque officia saepe natus ex, obcaecati ratione amet.
                Unde mollitia accusamus temporibus. Maxime quam ipsam corrupti, nemo minima at quae, nulla consequuntur vel eaque consectetur eum ducimus quo beatae fugit assumenda et voluptatem cumque amet officiis recusandae voluptatum?
                Quos reprehenderit velit iure. Hic fuga placeat laborum maiores, id necessitatibus iusto, incidunt beatae reiciendis ratione corrupti praesentium impedit quas quis explicabo nobis esse culpa inventore fugiat ipsa a? Perferendis.
                Error, ab aut quibusdam aliquid rerum et perspiciatis perferendis in, sapiente eius aperiam. Tempore animi exercitationem id, corrupti neque quis sequi reiciendis asperiores praesentium quasi doloribus unde natus. Dolores, voluptatibus.
                Nemo tempore consectetur nisi magnam harum itaque molestiae id voluptatum quam doloremque rerum consequuntur nostrum nobis eligendi, facere fugiat! Voluptatem corporis dignissimos, vel dolores corrupti adipisci iusto pariatur porro assumenda.
                Sapiente consectetur dignissimos tempore consequuntur labore corporis quam, expedita provident nesciunt libero atque delectus pariatur eveniet quo modi perferendis iusto veniam. Laborum porro quo, fugiat corrupti earum nihil nisi eveniet?
                Labore, voluptatum! Inventore tempora quia, facilis dolore, natus corrupti magni temporibus hic sapiente corporis quas accusamus praesentium beatae optio deleniti. Blanditiis culpa non officiis debitis quis repellendus quisquam nemo rem!
                Libero nisi eligendi maiores possimus atque. Qui enim ex omnis sequi libero, veniam nostrum quas aliquam, vero laboriosam necessitatibus nihil fugit dolore possimus provident? Excepturi ex voluptatibus ipsa quo animi.
                Eum nulla suscipit enim libero commodi numquam asperiores fugiat, sequi dolore optio doloremque. Dicta repellat laborum quo ab, fugit excepturi consectetur quidem delectus laudantium ad sunt voluptatum sit tenetur perspiciatis!
                Aut voluptatibus animi enim alias deserunt nostrum ut corrupti? Itaque, illum et animi error hic tempora nemo consequatur dolorem asperiores temporibus, quae excepturi doloremque eos ipsa at ut voluptas suscipit.
                Assumenda ex voluptatum laborum suscipit explicabo nostrum qui, sapiente, mollitia minima, dolorum debitis exercitationem excepturi perferendis architecto esse quo doloribus! Et voluptates error dignissimos deleniti ex vel culpa amet nihil?
                Perferendis sit cum dolores accusamus explicabo, nobis, atque tempore laborum, aspernatur voluptatibus quasi autem quae. Quo, illo placeat repudiandae cum suscipit doloremque, vitae facilis consequuntur est impedit, ipsam quis nam.
                Reprehenderit, aut. Recusandae odio nemo, asperiores praesentium ullam autem voluptatibus quia error ipsum doloribus. Voluptates eius, sunt deleniti, iste ullam error laborum cumque tempora est veritatis beatae vitae aliquid. Recusandae?
                Commodi expedita non eaque atque esse unde voluptates, nemo harum dignissimos perspiciatis. Dignissimos maxime rerum et tempora fugit ipsam officiis commodi eveniet veritatis, est autem atque. Voluptatum possimus beatae optio.
                Debitis consequuntur tempore impedit dolor quo fugit laudantium rem, illo ad, fugiat natus molestias cum corrupti eos? Fugit dignissimos saepe, officiis repellendus voluptas eius quae iusto animi ipsum impedit temporibus.
                Ipsum, laudantium. Commodi nisi quaerat sunt eaque necessitatibus possimus officia rem repudiandae aliquam, totam, quo dolorem dicta dolorum aliquid, eligendi harum aspernatur provident earum iste minima laudantium debitis. A, nulla.
                Autem, velit maiores! Suscipit neque velit autem nostrum eius numquam iusto ut veritatis nihil doloremque magnam nemo aliquid ex at quae aut quod rem qui tempore quis veniam, reprehenderit saepe?
                Accusantium reiciendis consectetur neque voluptates corrupti eveniet possimus laborum id aperiam? Voluptates iusto eveniet eligendi quas voluptas, facere dolores iure veniam voluptate, dicta distinctio non nulla! Tempore corrupti quis dicta.
                Tenetur, dicta incidunt. Quo quisquam voluptatibus omnis aspernatur aut! Distinctio sunt veritatis porro. Minima perspiciatis, ut nostrum nisi sequi harum sunt distinctio, ex alias quo quod earum dolores ab eligendi.
                Consequuntur tempore, est, eius quas, sit ut officia minus expedita odit quos repellendus? Labore cumque optio nostrum cupiditate inventore officia, accusantium, atque quidem ad culpa est natus ipsam ullam reprehenderit.
                Iusto, voluptatibus ullam recusandae sequi debitis voluptates illum quibusdam qui aperiam magni modi cumque quisquam laudantium. Officiis vero dolore, inventore eum reprehenderit, cum iusto magnam asperiores officia, modi eveniet molestias!
                Fugit velit explicabo dicta molestiae, blanditiis ullam alias neque cumque et ad incidunt expedita impedit consequatur id harum laborum a repellendus perferendis minus sapiente omnis. Doloribus, possimus saepe! Magni, quas.
                Illum ut, delectus labore, assumenda in illo consectetur cum laborum voluptas accusamus ipsam, voluptatum cumque culpa similique sapiente laudantium at doloribus minus praesentium a exercitationem enim aperiam reiciendis totam. Officia?
                Blanditiis, impedit labore iste, quis iure dolorem consectetur doloremque voluptas asperiores illum, minus ullam veritatis fuga unde harum facere nostrum reiciendis tempore nemo obcaecati. Consequatur provident exercitationem libero alias quos.
                Impedit dicta mollitia, odio accusamus voluptas aperiam expedita et unde illum nostrum ipsum vel hic? Iusto facere esse non natus, expedita repellat nam explicabo fugiat officiis provident, vel maiores. Ea.
                Atque officiis nam delectus! Totam aliquam repellat omnis deleniti ducimus, atque sit, explicabo earum labore eligendi ab! Quas aut odit culpa quasi iste et hic, accusamus dolorum suscipit ex earum?
                Error, fugiat doloribus. Earum eligendi veritatis libero perferendis, dolor voluptas quae adipisci quaerat consectetur dignissimos dolorem doloremque aut tenetur alias temporibus fugiat, autem eveniet maxime vero magnam quasi ea animi?
                Perferendis nemo laudantium maxime non illo, sint harum expedita labore blanditiis voluptates numquam. Voluptatibus illo praesentium quis repellendus deserunt. Veritatis maiores officia labore sint doloremque amet eum esse ratione. Eius.
                Necessitatibus, pariatur eaque. Sunt saepe voluptas est blanditiis ab quidem maiores accusamus, eos, quo similique ullam possimus omnis odit delectus iure voluptates consequatur quas esse reprehenderit culpa quae temporibus harum.
                Soluta nulla explicabo unde tenetur perspiciatis eligendi adipisci ullam eveniet, consectetur incidunt, dolor, eum tempore magnam delectus provident quia consequatur repellat! Fuga eius voluptatem quisquam magnam cum, eos ab est!
                Provident minima labore eum repellendus, earum molestiae cupiditate tenetur exercitationem voluptatem quaerat, aliquid explicabo ad consequuntur vitae reiciendis nesciunt commodi placeat maiores quibusdam iste dolore aperiam! Veritatis adipisci voluptatem labore.
                Dicta exercitationem consequuntur ratione, amet cumque, a sunt at voluptatem esse consectetur assumenda similique voluptate nisi maiores eligendi magnam beatae quidem ex? Autem in tenetur maxime unde temporibus rerum ad?
                In, repudiandae, ad rem architecto natus beatae itaque dignissimos omnis laudantium iure, molestias aperiam doloribus eius. Nobis laborum rem quam ullam doloribus autem nulla quis deserunt aliquam sed! Optio, placeat!
                Quae laudantium voluptatum dolor et minus perspiciatis beatae exercitationem accusantium labore aspernatur amet odio voluptate illo maiores qui, architecto illum assumenda necessitatibus quia molestias saepe veniam similique. Dolorum, dolorem iure.
                Labore accusamus suscipit non repudiandae. Necessitatibus fugiat doloremque maiores vitae nulla possimus velit, dolorem illum maxime autem. Neque suscipit nobis officia natus autem? Vitae assumenda architecto mollitia, a doloribus esse.
                Quidem, recusandae error cupiditate necessitatibus deleniti quod modi ullam sunt et provident expedita temporibus est labore alias accusamus a voluptates in. Provident accusamus laborum iusto repellendus tempora quis vero ab.
                Neque voluptates eveniet, id dolorem ad dolores voluptas aspernatur harum debitis dicta error blanditiis, quas possimus! Dolor voluptas aliquam fugiat! Itaque accusamus ex praesentium culpa impedit eaque deleniti facilis facere?
                Voluptatum officia blanditiis in, officiis totam dicta aspernatur sapiente provident magni porro ullam, sunt dignissimos assumenda! Obcaecati dolores deleniti aliquam, in excepturi inventore placeat distinctio, corrupti facilis non saepe. Soluta?
                Sint facilis blanditiis dolores harum excepturi voluptate ex. Ducimus vero expedita labore! Aliquam possimus, repudiandae suscipit voluptates dolor quos doloremque, ipsam harum odit nostrum eveniet, voluptatum error necessitatibus. Dolore, laudantium?
                Explicabo est, aperiam, error fuga, provident atque maiores dicta sint hic esse excepturi laudantium natus odio iure eveniet non perferendis quis iste et deleniti eaque iusto aliquam incidunt similique! Voluptates!
                Corrupti, ex aspernatur. Ea odio hic repellat voluptatum deleniti sequi saepe, illum officia optio error praesentium modi eos voluptate quidem labore. Laborum at quaerat ducimus consectetur laudantium explicabo recusandae. Quia!    
            </div>

        </>
    );
}
export default FileUploadDemo;